"""添加创收次数要求字段

Revision ID: 09aaa8220f6c
Revises: 29e2db3ff80a
Create Date: 2026-01-13 15:44:40.489002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09aaa8220f6c'
down_revision = '29e2db3ff80a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monetization_requirement', sa.String(length=10), nullable=True, comment='创收次数要求：3m/10m'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('monetization_requirement')

    # ### end Alembic commands ###
