"""添加 login_status 字段

Revision ID: 1680069e0853
Revises: 
Create Date: 2026-01-09 15:46:49.438152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1680069e0853'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_status', sa.String(length=50), nullable=True, comment='登录状态'))
        batch_op.add_column(sa.Column('browser_env_id', sa.String(length=100), nullable=True, comment='浏览器环境ID'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('browser_env_id')
        batch_op.drop_column('login_status')

    # ### end Alembic commands ###
