"""添加频道状态以及频道链接字段

Revision ID: 29e2db3ff80a
Revises: 8f4d563bc0d7
Create Date: 2026-01-12 16:14:13.903148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29e2db3ff80a'
down_revision = '8f4d563bc0d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel_status', sa.String(length=50), nullable=True, comment='频道状态：not_created/created/failed'))
        batch_op.add_column(sa.Column('channel_url', sa.String(length=500), nullable=True, comment='频道链接'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('channel_url')
        batch_op.drop_column('channel_status')

    # ### end Alembic commands ###
