"""添加账号手机号关联字段

Revision ID: 8f4d563bc0d7
Revises: 1680069e0853
Create Date: 2026-01-10 10:14:56.183360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f4d563bc0d7'
down_revision = '1680069e0853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_id', sa.Integer(), nullable=True, comment='绑定的手机号ID'))
        batch_op.create_foreign_key(None, 'phones', ['phone_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('phone_id')

    # ### end Alembic commands ###
